/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as LandingRouteRouteImport } from './routes/_landing/route'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as LandingIndexRouteImport } from './routes/_landing/index'
import { Route as DashboardExampleWideRouteImport } from './routes/dashboard/example-wide'
import { Route as DashboardExamplePageRouteImport } from './routes/dashboard/example-page'
import { Route as DashboardExampleCanvasRouteImport } from './routes/dashboard/example-canvas'
import { Route as LandingPricingRouteImport } from './routes/_landing/pricing'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRouteRoute = LandingRouteRouteImport.update({
  id: '/_landing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const LandingIndexRoute = LandingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LandingRouteRoute,
} as any)
const DashboardExampleWideRoute = DashboardExampleWideRouteImport.update({
  id: '/example-wide',
  path: '/example-wide',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardExamplePageRoute = DashboardExamplePageRouteImport.update({
  id: '/example-page',
  path: '/example-page',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardExampleCanvasRoute = DashboardExampleCanvasRouteImport.update({
  id: '/example-canvas',
  path: '/example-canvas',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const LandingPricingRoute = LandingPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => LandingRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LandingIndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/pricing': typeof LandingPricingRoute
  '/dashboard/example-canvas': typeof DashboardExampleCanvasRoute
  '/dashboard/example-page': typeof DashboardExamplePageRoute
  '/dashboard/example-wide': typeof DashboardExampleWideRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/pricing': typeof LandingPricingRoute
  '/dashboard/example-canvas': typeof DashboardExampleCanvasRoute
  '/dashboard/example-page': typeof DashboardExamplePageRoute
  '/dashboard/example-wide': typeof DashboardExampleWideRoute
  '/': typeof LandingIndexRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_landing': typeof LandingRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/_landing/pricing': typeof LandingPricingRoute
  '/dashboard/example-canvas': typeof DashboardExampleCanvasRoute
  '/dashboard/example-page': typeof DashboardExamplePageRoute
  '/dashboard/example-wide': typeof DashboardExampleWideRoute
  '/_landing/': typeof LandingIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/pricing'
    | '/dashboard/example-canvas'
    | '/dashboard/example-page'
    | '/dashboard/example-wide'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/pricing'
    | '/dashboard/example-canvas'
    | '/dashboard/example-page'
    | '/dashboard/example-wide'
    | '/'
    | '/dashboard'
  id:
    | '__root__'
    | '/_landing'
    | '/dashboard'
    | '/_landing/pricing'
    | '/dashboard/example-canvas'
    | '/dashboard/example-page'
    | '/dashboard/example-wide'
    | '/_landing/'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LandingRouteRoute: typeof LandingRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing': {
      id: '/_landing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LandingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_landing/': {
      id: '/_landing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LandingIndexRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/dashboard/example-wide': {
      id: '/dashboard/example-wide'
      path: '/example-wide'
      fullPath: '/dashboard/example-wide'
      preLoaderRoute: typeof DashboardExampleWideRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/example-page': {
      id: '/dashboard/example-page'
      path: '/example-page'
      fullPath: '/dashboard/example-page'
      preLoaderRoute: typeof DashboardExamplePageRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/example-canvas': {
      id: '/dashboard/example-canvas'
      path: '/example-canvas'
      fullPath: '/dashboard/example-canvas'
      preLoaderRoute: typeof DashboardExampleCanvasRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_landing/pricing': {
      id: '/_landing/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof LandingPricingRouteImport
      parentRoute: typeof LandingRouteRoute
    }
  }
}

interface LandingRouteRouteChildren {
  LandingPricingRoute: typeof LandingPricingRoute
  LandingIndexRoute: typeof LandingIndexRoute
}

const LandingRouteRouteChildren: LandingRouteRouteChildren = {
  LandingPricingRoute: LandingPricingRoute,
  LandingIndexRoute: LandingIndexRoute,
}

const LandingRouteRouteWithChildren = LandingRouteRoute._addFileChildren(
  LandingRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardExampleCanvasRoute: typeof DashboardExampleCanvasRoute
  DashboardExamplePageRoute: typeof DashboardExamplePageRoute
  DashboardExampleWideRoute: typeof DashboardExampleWideRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardExampleCanvasRoute: DashboardExampleCanvasRoute,
  DashboardExamplePageRoute: DashboardExamplePageRoute,
  DashboardExampleWideRoute: DashboardExampleWideRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LandingRouteRoute: LandingRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
